FormulárioTeste/Models/Brinquedo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FormulárioTeste.Models
{
    public class Brinquedo
    {
        public int Id { get; set; }

        public string Nome { get; set; }

        public string Industria { get; set; }
    }
}

FormulárioTeste/Models/ErrorViewModel.cs
using System;

namespace FormulárioTeste.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FormulárioTeste/Models/Livro.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FormulárioTeste.Models
{
    public class Livro
    {
        public int Id { get; set; }

        public string Autor { get; set; }

        public string Titulo { get; set; }
    }
}

FormulárioTeste/Models/ViewModels/BrinquedoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FormulárioTeste.Models.ViewModels
{
    public class BrinquedoViewModel
    {
        public BrinquedoViewModel(Brinquedo brinquedo)
        {
            this.brinquedo = brinquedo;
        }

        public Brinquedo brinquedo { get; set; }
    }
}

FormulárioTeste/Models/ViewModels/LivroViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FormulárioTeste.Models.ViewModels
{
    public class LivroViewModel
    {
        public LivroViewModel(Livro livro)
        {
            Livro = livro;
        }
                                            
        public Livro Livro { get; set; }
    }
}

FormulárioTeste/Models/ViewModels/PreteleiraViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FormulárioTeste.Models.ViewModels
{
    public class PreteleiraViewModel
    {
        public int id { get; set; }

        public Livro livro { get; set; }

        public Brinquedo brinquedo { get; set; }

    }
}

FormulárioTeste/Controllers/HomeController.cs
using FormulárioTeste.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FormulárioTeste.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FormulárioTeste/Controllers/PrateleiraController.cs
using FormulárioTeste.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FormulárioTeste.Controllers
{
    public class PrateleiraController : Controller
    {
        PreteleiraViewModel model;
        public IActionResult Index()
        {
            model = new PreteleiraViewModel();
            model.id = 10;
            return View(model);
        }


        public IActionResult GravaDados(PreteleiraViewModel model)
        {
            return View("Index",model);

        }
    }
}

FormulárioTeste/ViewComponents/Prateleira/BrinquedoViewComponent.cs
using FormulárioTeste.Models;
using FormulárioTeste.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FormulárioTeste.ViewComponents.Prateleira
{
    public class BrinquedoViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(Brinquedo brinquedo)
        {
            return View("Default", new BrinquedoViewModel(brinquedo));
        }
    }
}

FormulárioTeste/ViewComponents/Prateleira/LivroViewComponent.cs
using FormulárioTeste.Models;
using FormulárioTeste.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FormulárioTeste.ViewComponents.Prateleira
{
    public class LivroViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(Livro livro)
        {
            return View("Default", new LivroViewModel(livro));
        }
    }
}

FormulárioTeste/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FormulárioTeste/Views/Prateleira/Components/Brinquedo/Default.cshtml
@model FormulárioTeste.Models.ViewModels.BrinquedoViewModel

<div>
    <label>Id do brinquedo</label>
    <input type="text" asp-for="@(Model.brinquedo.Id)" />
</div>
<div>
    <label>Industria do brinquedo</label>
    <input type="text" asp-for="@(Model.brinquedo.Industria)" />
</div>
<div>
    <label>Nome do brinquedo</label>
    <input type="text" asp-for="@(Model.brinquedo.Nome)" />
</div>

FormulárioTeste/Views/Prateleira/Components/Livro/Default.cshtml
@model FormulárioTeste.Models.ViewModels.LivroViewModel


<div>
    <label>Autor do Livro</label>
    <input type="text" asp-for="@(Model.Livro.Autor)" />
</div>
<div>
    <label>Id do Livro</label>
    <input type="text" asp-for="@(Model.Livro.Id)" />
</div>
<div>
    <label>Titulo do Livro</label>
    <input type="text" asp-for="@(Model.Livro.Titulo)" />
</div>

FormulárioTeste/Views/Prateleira/Index.cshtml
@addTagHelper *, FormulárioTeste
@model  FormulárioTeste.Models.ViewModels.PreteleiraViewModel
@{
    ViewData["Title"] = "PrateleiraView";
}

<h1>PrateleiraView</h1>
<div>
    @using(Html.BeginForm("GravaDados", "Prateleira", FormMethod.Post))
    {
        <div>
            <label>PrateleiraId</label>
            <input type="text" asp-for="@(Model.id)" />
        </div>
        <vc:livro Livro="@Model.livro" />
        <vc:brinquedo brinquedo="@Model.brinquedo"/>        

        <input type="submit" name="Salvar" />
    }
</div>

FormulárioTeste/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FormulárioTeste</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FormulárioTeste</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FormulárioTeste - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>